# Generated by Django 5.1.4 on 2025-01-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='news_file',
            field=models.FileField(blank=True, null=True, upload_to='website files'),
        ),
    ]
