# Generated by Django 5.1.5 on 2025-06-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cvsubmission',
            old_name='department',
            new_name='unit',
        ),
        migrations.RemoveField(
            model_name='cvsubmission',
            name='center_or_unit',
        ),
        migrations.RemoveField(
            model_name='cvsubmission',
            name='faculty',
        ),
        migrations.AlterField(
            model_name='computerskill',
            name='proficiency',
            field=models.CharField(choices=[('basic', 'Basic'), ('good', 'Good'), ('excellent', 'Excellent')], max_length=9),
        ),
        migrations.AlterField(
            model_name='cvsubmission',
            name='age_bracket',
            field=models.CharField(choices=[('20-30', '20-30 years'), ('31-40', '31-40 years'), ('41-50', '41-50 years'), ('51-60', '51-60 years'), ('61+', '61+ years')], max_length=5),
        ),
        migrations.AlterField(
            model_name='languageskill',
            name='proficiency',
            field=models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('fluent', 'Fluent')], max_length=12),
        ),
        migrations.AlterField(
            model_name='professionalmembership',
            name='membership_type',
            field=models.CharField(choices=[('graduate', 'Graduate Member'), ('associate', 'Associate Member'), ('full', 'Full Member'), ('fellow', 'Fellow')], max_length=9),
        ),
    ]
