# Generated by Django 5.1.5 on 2025-06-10 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_rename_department_cvsubmission_unit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cvsubmission',
            options={},
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('unit_type', models.CharField(choices=[('faculty', 'Faculty'), ('department', 'Department'), ('institute', 'Institute'), ('center', 'Center/Directorate')], max_length=20)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='cv.unit')),
            ],
        ),
        migrations.AlterField(
            model_name='cvsubmission',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cv.unit'),
        ),
    ]
