# Generated by Django 5.1.5 on 2025-06-16 14:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_alter_award_year_alter_education_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalproject',
            name='role',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('amount', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)])),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='cv.cvsubmission')),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
    ]
